version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./images/nginx:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
    php:
        build: ./images/php
        volumes:
            - ./www:/var/www
    db:
        image: mariadb
        ports:
            - "3306:3306"
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: dbpass
    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"